const dishesData = [
    { name: "Builder Ramen", price: 14.40 },
    { name: "Vegan Ramen", price: 12.70 },
    { name: "Spicy Ramen", price: 13.90 },
    { name: "Tonkotsu Ramen", price: 15.50 },
    { name: "Shoyu Ramen", price: 14.00 },
    { name: "Shio Ramen", price: 14.20 },
    { name: "Miso Ramen", price: 14.10 },
    { name: "Tsukemen", price: 15.00 },
    { name: "Tantanmen", price: 14.80 },
    { name: "Karaage", price: 6.50 },
    { name: "Gyoza", price: 5.50 },
    { name: "Edamame", price: 4.50 },
    { name: "Karaage Bao", price: 6.90 },
    { name: "Katsu Curry", price: 15.00 },
    { name: "Karaage Curry", price: 14.50 },
    { name: "Karaage Don", price: 14.00 },
    { name: "Katsu Don", price: 14.50 },
    { name: "Karaage Udon", price: 12.50 },
    { name: "Katsu Udon", price: 13.00 },
    { name: "Karaage Soba", price: 12.50 },
    { name: "Katsu Soba", price: 13.00 },
    { name: "Karaage Ramen", price: 14.00 },
    { name: "Katsu Ramen", price: 14.50 },
    { name: "Karaage Bento", price: 12.50 },
    { name: "Katsu Bento", price: 13.00 },
    // Add more dishes as needed
];