const dishesData = [
  { name: "Builder Ramen", price: 14.4, category: "hauptspeisen" },
  { name: "Vegan Ramen", price: 12.7, category: "hauptspeisen" },
  { name: "Spicy Ramen", price: 13.9, category: "hauptspeisen" },
  { name: "Tonkotsu Ramen", price: 15.5, category: "hauptspeisen" },
  { name: "Shoyu Ramen", price: 14.0, category: "hauptspeisen" },
  { name: "Shio Ramen", price: 14.2, category: "hauptspeisen" },
  { name: "Miso Ramen", price: 14.1, category: "hauptspeisen" },
  { name: "Tsukemen", price: 15.0, category: "hauptspeisen" },
  { name: "Tantanmen", price: 14.8, category: "hauptspeisen" },
  { name: "Karaage", price: 6.5, category: "vorspeisen" },
  { name: "Gyoza", price: 5.5, category: "vorspeisen" },
  { name: "Edamame", price: 4.5, category: "vorspeisen" },
  { name: "Karaage Bao", price: 6.9, category: "vorspeisen" },
  { name: "Katsu Curry", price: 15.0, category: "hauptspeisen" },
  { name: "Karaage Curry", price: 14.5, category: "hauptspeisen" },
  { name: "Karaage Don", price: 14.0, category: "hauptspeisen" },
  { name: "Katsu Don", price: 14.5, category: "hauptspeisen" },
  { name: "Karaage Udon", price: 12.5, category: "hauptspeisen" },
  { name: "Katsu Udon", price: 13.0, category: "hauptspeisen" },
  { name: "Karaage Soba", price: 12.5, category: "hauptspeisen" },
  { name: "Katsu Soba", price: 13.0, category: "hauptspeisen" },
  { name: "Karaage Ramen", price: 14.0, category: "hauptspeisen" },
  { name: "Katsu Ramen", price: 14.5, category: "hauptspeisen" },
  { name: "Karaage Bento", price: 12.5, category: "hauptspeisen" },
  { name: "Katsu Bento", price: 13.0, category: "hauptspeisen" },
  { name: "Green Tea", price: 2.5, category: "getraenke" },
  { name: "Sake", price: 5.0, category: "getraenke" },
  { name: "Mochi", price: 3.5, category: "nachspeisen" },
  { name: "Dorayaki", price: 4.0, category: "nachspeisen" },
];
