const dishesData = [
    { name: "Builder Ramen", price: 14.40, category: "hauptspeisen" },
    { name: "Vegan Ramen", price: 12.70, category: "hauptspeisen" },
    { name: "Spicy Ramen", price: 13.90, category: "hauptspeisen" },
    { name: "Tonkotsu Ramen", price: 15.50, category: "hauptspeisen" },
    { name: "Shoyu Ramen", price: 14.00, category: "hauptspeisen" },
    { name: "Shio Ramen", price: 14.20, category: "hauptspeisen" },
    { name: "Miso Ramen", price: 14.10, category: "hauptspeisen" },
    { name: "Tsukemen", price: 15.00, category: "hauptspeisen" },
    { name: "Tantanmen", price: 14.80, category: "hauptspeisen" },
    { name: "Karaage", price: 6.50, category: "vorspeisen" },
    { name: "Gyoza", price: 5.50, category: "vorspeisen" },
    { name: "Edamame", price: 4.50, category: "vorspeisen" },
    { name: "Karaage Bao", price: 6.90, category: "vorspeisen" },
    { name: "Katsu Curry", price: 15.00, category: "hauptspeisen" },
    { name: "Karaage Curry", price: 14.50, category: "hauptspeisen" },
    { name: "Karaage Don", price: 14.00, category: "hauptspeisen" },
    { name: "Katsu Don", price: 14.50, category: "hauptspeisen" },
    { name: "Karaage Udon", price: 12.50, category: "hauptspeisen" },
    { name: "Katsu Udon", price: 13.00, category: "hauptspeisen" },
    { name: "Karaage Soba", price: 12.50, category: "hauptspeisen" },
    { name: "Katsu Soba", price: 13.00, category: "hauptspeisen" },
    { name: "Karaage Ramen", price: 14.00, category: "hauptspeisen" },
    { name: "Katsu Ramen", price: 14.50, category: "hauptspeisen" },
    { name: "Karaage Bento", price: 12.50, category: "hauptspeisen" },
    { name: "Katsu Bento", price: 13.00, category: "hauptspeisen" },
    { name: "Green Tea", price: 2.50, category: "getraenke" },
    { name: "Sake", price: 5.00, category: "getraenke" },
    { name: "Mochi", price: 3.50, category: "nachspeisen" },
    { name: "Dorayaki", price: 4.00, category: "nachspeisen" },
    // Add more dishes as needed
];